EPMRPP-60619 Update vulnerabilities
reportportal/agent-js-cypress pull request #82
Opened 2021-04-26 14:14 UTC by katrin-kot

2021-04-26 14:56 UTC, KatsiarynaTatarynovich requested changes

2021-04-26 14:56 UTC, KatsiarynaTatarynovich commented on package.json
> +    "axios": "^0.21.1",
Why did you add `axios`?

2021-04-26 15:59 UTC, katrin-kot commented on package.json
> +    "axios": "^0.21.1",
I deleted axios

2021-04-27 07:33 UTC, KatsiarynaTatarynovich approved these changes

2021-04-27 07:37 UTC, merged